// services/api.ts
import { createApi } from '@reduxjs/toolkit/query/react';
import { baseQuery } from './baseQuery';

export const api = createApi({
  reducerPath: 'api',
  baseQuery: baseQuery,
  tagTypes: [
    'auth',
    'get_summary',
    'get_users',
    'get_user_settings',
    'get_clients',
    'get_projects',
    'get_master_phases',
    'get_master_tasks',
    'get_project_phases',
    'get_project_task',
    'get_projectTypes',
    'get_roles',
    'get_users',
    'upload',
    'get_timelines',
    'get_project_tasks',
    'get_tasks',
    'get_phases',
    'edit_task',
    'get_project_quotations',
    'get_project_snags',
    'get_project_site_visits',
    'site_visit_gallery',
    'get_project_summary',
    'get_vendors',
    'get_specializations',
    'get_product_categories',
    'get_product_sub_categories',
    'get_product_sub_categories',
    'get_product_brand',
    'get_product',
    'get_activities',
    'get_project_activities',
    'get_comments',
    'get_phases_by_project_type',
    'get_file_manager',
    'get_folders',
    'get_folder_contents',
    'get_moms',
    'get_subtasks',
    'get_payments',
    'get_policies',
    'get_designations',
    'get_project_type_groups',
    'get_timesheets',
    'get_timesheet_approvals',
    'get_organization',
    'get_notifications',
    'get_endpoints',
    'get_permissions',
    'get_role_permissions',
    'get_departments',
    'get_module_definitions',
    'get_module_access',
    'get_unit',
    'get_area',
  ],
  endpoints: () => ({}),
});
