export const ELEMENT_LIBRARY_TABLE_DATA = [
  {
    id: 1,
    libraryName: "McDonald's Store",
    typeOfLibrary: 'Interior Library',
    createdBy: 'Ravi Kumar',
    lastUpdated: {
      date: '23 May 2025, 11:31 AM',
      user: 'Ravi Kumar',
    },
    section: 1,
    elements: 67,
  },
  {
    id: 1,
    libraryName: "McDonald's Store",
    typeOfLibrary: 'Interior Library',
    createdBy: 'Ravi Kumar',
    lastUpdated: {
      date: '23 May 2025, 11:31 AM',
      user: 'Ravi Kumar',
    },
    section: 1,
    elements: 67,
  },
  {
    id: 1,
    libraryName: "McDonald's Store",
    typeOfLibrary: 'Interior Library',
    createdBy: 'Ravi Kumar',
    lastUpdated: {
      date: '23 May 2025, 11:31 AM',
      user: 'Ravi Kumar',
    },
    section: 1,
    elements: 67,
  },
  {
    id: 1,
    libraryName: "McDonald's Store",
    typeOfLibrary: 'Interior Library',
    createdBy: 'Ravi Kumar',
    lastUpdated: {
      date: '23 May 2025, 11:31 AM',
      user: 'Ravi Kumar',
    },
    section: 1,
    elements: 67,
  },
  {
    id: 1,
    libraryName: "McDonald's Store",
    typeOfLibrary: 'Interior Library',
    createdBy: 'Ravi Kumar',
    lastUpdated: {
      date: '23 May 2025, 11:31 AM',
      user: 'Ravi Kumar',
    },
    section: 1,
    elements: 67,
  },
];

export const RATE_CONTRACTS_TABLE_DATA = [
  {
    id: 1,
    vendorNameAndId: {
      name: 'Test Org',
      id: 'RDVDR67678',
    },
    buyerName: 'Name Buyer',
    contractName: 'Contract Name',
    vendorCategory: 'Category Here',
    createdBy: 'Ravi Kumar',
    startFrom: '24 May 2025',
    validThrough: '24 May 2025',
    status: 'in-progress',
    attachment: 'file.jpg',
  },
  {
    id: 2,
    vendorNameAndId: {
      name: 'Test Org',
      id: 'RDVDR67678',
    },
    buyerName: 'Name Buyer',
    contractName: 'Contract Name',
    vendorCategory: 'Category Here',
    createdBy: 'Ravi Kumar',
    startFrom: '24 May 2025',
    validThrough: '24 May 2025',
    status: 'in-progress',
    attachment: 'file.jpg',
  },
  {
    id: 3,
    vendorNameAndId: {
      name: 'Test Org',
      id: 'RDVDR67678',
    },
    buyerName: 'Name Buyer',
    contractName: 'Contract Name',
    vendorCategory: 'Category Here',
    createdBy: 'Ravi Kumar',
    startFrom: '24 May 2025',
    validThrough: '24 May 2025',
    status: 'in-progress',
    attachment: 'file.jpg',
  },
  {
    id: 4,
    vendorNameAndId: {
      name: 'Test Org',
      id: 'RDVDR67678',
    },
    buyerName: 'Name Buyer',
    contractName: 'Contract Name',
    vendorCategory: 'Category Here',
    createdBy: 'Ravi Kumar',
    startFrom: '24 May 2025',
    validThrough: '24 May 2025',
    status: 'in-progress',
    attachment: 'file.jpg',
  },
  {
    id: 5,
    vendorNameAndId: {
      name: 'Test Org',
      id: 'RDVDR67678',
    },
    buyerName: 'Name Buyer',
    contractName: 'Contract Name',
    vendorCategory: 'Category Here',
    createdBy: 'Ravi Kumar',
    startFrom: '24 May 2025',
    validThrough: '24 May 2025',
    status: 'in-progress',
    attachment: 'file.jpg',
  },
  {
    id: 6,
    vendorNameAndId: {
      name: 'Test Org',
      id: 'RDVDR67678',
    },
    buyerName: 'Name Buyer',
    contractName: 'Contract Name',
    vendorCategory: 'Category Here',
    createdBy: 'Ravi Kumar',
    startFrom: '24 May 2025',
    validThrough: '24 May 2025',
    status: 'in-progress',
    attachment: 'file.jpg',
  },
];
