import express from 'express';
import auth from './auth.routes.js';
import user from './user.routes.js';
import roles from './roles.routes.js';
import permissions from './permission.routes.js';
import endpoints from './endpoints.routes.js';
import tasks from './task.routes.js';
import phase from './phase.routes.js';
import project from './project.routes.js';
import client from './client.route.js';
import upload from './upload.routes.js';
import quotations from './quotations.routes.js';
import masterPhase from './master/masterPhase.routes.js';
import masterTask from './master/masterTask.routes.js';
import projectType from './projectType.router.js';
import projectTypeGroup from './projectTypeGroup.routes.js';
import timeline from './timeline.routes.js';
import comment from './comment.routes.js';
import subTask from './subTask.routes.js';
import vendor from './vendor.routes.js';
import masterItem from './master/masterItem.routes.js';
import category from './category.routes.js';
import fileManager from './fileManager.routes.js';
import activities from './activities.routes.js';
import summary from './summary.routes.js';
import snag from './snag.routes.js';
import mom from './mom.routes.js';
import settings from './settings/settings.routes.js';
import payment from './payment.routes.js';
import deliverable from './deliverable.routes.js';
import siteVisit from './siteVisit.routes.js';
import pincode from './pincode.routes.js';
import sidebar from './sidebar.routes.js';
import timesheet from './timesheet.routes.js';
import notification from './notification.routes.js';
import moduleAccess from './moduleAccess.routes.js';
import unit from './unit.routes.js';
import area from './area.routes.js';

const app = express();

app.use('/auth', auth);
app.use('/users', user);
app.use('/roles', roles);
app.use('/permissions', permissions);
app.use('/endpoints', endpoints);
app.use('/task', tasks);
app.use('/project-type', projectType);
app.use('/project-type-group', projectTypeGroup);
app.use('/phase', phase);
app.use('/project', project);
app.use('/client', client);
app.use('/upload', upload);
app.use('/quotations', quotations);
app.use('/masterPhase', masterPhase);
app.use('/masterTask', masterTask);
app.use('/masterItem', masterItem);
app.use('/timeline', timeline);
app.use('/comment', comment);
app.use('/subTask', subTask);
app.use('/vendor', vendor);
app.use('/category', category);
app.use('/file-manager', fileManager);
app.use('/activities', activities);
app.use('/summary', summary);
app.use('/snag', snag);
app.use('/mom', mom);
app.use('/settings', settings);
app.use('/payment', payment);
app.use('/deliverable', deliverable);
app.use('/site-visit', siteVisit);
app.use('/pincode', pincode);
app.use('/sidebar', sidebar);
app.use('/timesheet', timesheet);
app.use('/notifications', notification);
app.use('/module-access', moduleAccess);
app.use('/unit', unit);
app.use('/area', area);

export default app;
