export const timeDetailsTableHeaders = [
  { title: 'S. No.', sortingRequired: false },
  { title: 'Name', sortingRequired: false },
  { title: 'Duration', sortingRequired: true },
  { title: 'Planned Start', sortingRequired: true },
  { title: 'Planned End', sortingRequired: true },
  { title: 'Predecessor Task', sortingRequired: false },
  { title: 'Assigned To', sortingRequired: true },
  { title: 'Assigned By', sortingRequired: false },
  { title: 'Delayed By', sortingRequired: false },
];
export const TIMELINE_DETAIL_TABLE_DATA = [
  {
    sNo: 1,
    name: 'Create a logo',
    duration: '1 Day',
    plannedStart: '14 May 2025',
    plannedEnd: '14 May 2025',
    predecesarTask: 'Select Predecessor',
    assignedTo: 'Not Assigned',
    assignedBy: 'Kavin',
    delayedBy: '0',
  },
  {
    sNo: 2,
    name: 'Create a logo',
    duration: '1 Day',
    plannedStart: '14 May 2025',
    plannedEnd: '14 May 2025',
    predecesarTask: 'Select Predecessor',
    assignedTo: 'Not Assigned',
    assignedBy: 'Kavin',
    delayedBy: '0',
  },
  {
    sNo: 3,
    name: 'Create a logo',
    duration: '1 Day',
    plannedStart: '14 May 2025',
    plannedEnd: '14 May 2025',
    predecesarTask: 'Select Predecessor',
    assignedTo: 'Not Assigned',
    assignedBy: 'Kavin',
    delayedBy: '0',
  },
  {
    sNo: 4,
    name: 'Create a logo',
    duration: '1 Day',
    plannedStart: '14 May 2025',
    plannedEnd: '14 May 2025',
    predecesarTask: 'Select Predecessor',
    assignedTo: 'Not Assigned',
    assignedBy: 'Kavin',
    delayedBy: '0',
  },
];
